# Generated by Django 4.1 on 2022-08-10 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_name',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
