# Generated by Django 4.1 on 2022-08-10 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_sale_date_of_purchase_alter_product_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_of_purchase',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 8, 10, 13, 22, 43), max_length=255, null=True),
        ),
    ]
