# Generated by Django 4.1 on 2022-08-10 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_alter_sale_amount_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_of_purchase',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 8, 10, 15, 15, 1), max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
