# Generated by Django 4.1 on 2022-08-10 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_alter_sale_date_of_purchase_alter_sale_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_of_purchase',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 8, 10, 15, 16, 13), max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
