# Generated by Django 4.1 on 2022-08-10 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_alter_product_unit_price_alter_sale_date_of_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_of_purchase',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 8, 10, 15, 19, 25), max_length=255, null=True),
        ),
    ]
