# Generated by Django 4.1 on 2022-08-10 09:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_alter_sale_date_of_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='issued_quantity',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(models.PositiveIntegerField(default=0, null=True))]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_of_purchase',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 8, 10, 17, 15, 15), max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(0)]),
        ),
    ]
